/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_togrulseyid_prizmatagram_natives_NativeClass */

#ifndef _Included_com_togrulseyid_prizmatagram_natives_NativeClass
#define _Included_com_togrulseyid_prizmatagram_natives_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_getStringFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    myNativeFunction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_myNativeFunction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeDithering
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeDithering
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeMosaic
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeMosaic
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeTelevision
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeTelevision
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativePixelize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativePixelize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativePixelate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativePixelate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeOilPaint
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeOilPaint
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeFishEye
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeFishEye
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    cartoonifyImage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_cartoonifyImage
  (JNIEnv *, jobject, jint, jint, jbyteArray, jintArray, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    ShowPreview
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_ShowPreview
  (JNIEnv *, jobject, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeFlip
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeFlip
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeMirror
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeMirror
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeTest
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeTest
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
