/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_togrulseyid_prizmatagram_natives_NativeClass */

#ifndef _Included_com_togrulseyid_prizmatagram_natives_NativeClass
#define _Included_com_togrulseyid_prizmatagram_natives_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_getStringFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    myNativeFunction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_myNativeFunction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeDithering
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeDithering
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeMosaic
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeMosaic
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeTelevision
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeTelevision
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativePixelize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativePixelize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeTest
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeTest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_togrulseyid_prizmatagram_natives_NativeClass
 * Method:    nativeOilPaint
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_togrulseyid_prizmatagram_natives_NativeClass_nativeOilPaint
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
